spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/kofood
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  flyway:
    driver-class-name: org.postgresql.Driver
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URI}:${DB_PORT}/kofood
