spring:

  application:
    name: pagamentos-ms

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pagamentos
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: on
    properties:
      hibernate:
        format_sql: true

  flyway:
    driver-class-name: org.postgresql.Driver
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/pagamentos
    validate-on-migrate: false
    baseline-on-migrate: true

  rabbitmq:
    host: localhost
    port: 5672
    username: kofood
    password: kofood

server:
  port: 0


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      updatePayment:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30000

