spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kofood-pagamentos
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    show-sql: on
    properties:
      hibernate:
        format_sql: true


  flyway:
    driver-class-name: org.postgresql.Driver
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/kofood-pagamentos
    validate-on-migrate: false
    baseline-on-migrate: true

  application:
    name: pagamentos-ms

server:
  port: 0


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      updatePayment:
        sliding-window-size: 3
        minimum-number-of-calls: 2
        wait-duration-in-open-state:
          seconds: 90
